name: GitHub sync test

on:
  workflow_dispatch:

permissions: read-all

jobs:
  gh-sync:
    name: dump-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
      - name: set token
        run: echo ${{ secrets.AUGGIE_BOT_TOKEN }} > token
      - name: GitHub sync
        uses: docker://ghcr.io/relengfam/peribolos:latest
        with:
          github-token-path: ./token
          dump: uwu-tools
