name: GitHub sync tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: read-all

jobs:
  test-dump:
    name: dump-config
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set GitHub token
        run: echo ${{ secrets.AUGGIE_BOT_TOKEN }} > token

      - name: Dump org config
        uses: docker://ghcr.io/uwu-tools/peribolos:v0.0.3@sha256:03b7dc21ec9a18ded7d73175b5920e815cb672fe03e56dbd8ef2a3dc2595ff91
        with:
          github-token-path: ./token
          dump: relengfam

  test-sync:
    name: sync-orgs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set GitHub token
        run: echo ${{ secrets.AUGGIE_BOT_TOKEN }} > token

      - name: Sync GitHub orgs
        uses: docker://ghcr.io/uwu-tools/peribolos:v0.0.3@sha256:03b7dc21ec9a18ded7d73175b5920e815cb672fe03e56dbd8ef2a3dc2595ff91
        with:
          github-token-path: ./token
          config-path: orgs
          min-admins: 3
          required-admins: "auggie-bot,cpanato,justaugustus"
          fix-org: true
          fix-org-members: true
          fix-teams: true
          fix-team-members: true
          fix-team-repos: true
