name: GitHub sync tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions: read-all

jobs:
  test-dump:
    name: dump-config
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set GitHub token
        run: echo ${{ secrets.AUGGIE_BOT_TOKEN }} > token

      - name: Dump org config
        uses: docker://ghcr.io/uwu-tools/peribolos:v0.0.3@sha256:03b7dc21ec9a18ded7d73175b5920e815cb672fe03e56dbd8ef2a3dc2595ff91
        with:
          github-token-path: ./token
          dump: relengfam

  test-sync:
    name: sync-orgs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Set GitHub token
        run: echo ${{ secrets.AUGGIE_BOT_TOKEN }} > token

      - name: Sync GitHub orgs
        uses: docker://ghcr.io/uwu-tools/peribolos:v0.0.3@sha256:03b7dc21ec9a18ded7d73175b5920e815cb672fe03e56dbd8ef2a3dc2595ff91
        with:
          github-token-path: ./token
          config-path: orgs
          min-admins: 3
          required-admins: "auggie-bot,cpanato,justaugustus"
          fix-org: true
          fix-org-members: true
          fix-teams: true
          fix-team-members: true
          fix-team-repos: true
